### ISSUE TITLE
文本摘要里有篇论文的链接错了

### ISSUE THREAD

**Issue by wizardrobot1** [changwookjun/nlp-paper#1]
文本摘要里这篇论文的链接错了：
A Discourse-Aware Attention Model for Abstractive Summarization of Long Documents - Arman Cohan(2018)
点进去是GENERATING WIKIPEDIA BY SUMMARIZING LONG SEQUENCES - Peter J. Liu(2018)的

**Comment by changwookjun** [comment]
corrected the content.
Thank you for your consideration.
